language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false

git:
    submodules: true

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=JeePower2.ino

install:
    - pip install -U platformio

before_script:
    - cd kylegordon/JeePower2
    - git submodule update --init --recursive

script:
    - platformio ci --board=uno
